# Generated by Django 4.0.4 on 2022-05-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_buy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=9000)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=130)),
                ('address', models.CharField(max_length=2000)),
                ('country', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('zip', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Orderupdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_description', models.CharField(max_length=9000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
